version: "3.8"
services:
    # PHP service
    app:
        build: .
        container_name: screenbuilder_app
        working_dir: /var/www/
        volumes:
            - ./:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app-network
    # MySQL database service
    mysql:
        platform: linux/x86_64
        image: mysql:5.7
        container_name: screenbuilder_mysql
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: root
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./docker/mysql:/var/lib/mysql
        networks:
            - app-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on:
            - mysql
        container_name: screenbuilder_phpmyadmin
        restart: unless-stopped
        ports:
            - 8080:80
        environment:
            UPLOAD_LIMIT: 1G
            PMA_HOST: mysql
            PMA_PORT: 3306
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        links:
            - mysql
        networks:
            - app-network

    # Nginx service
    nginx:
        image: nginx:alpine
        container_name: screenbuilder_nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network

networks:
    app-network:
        driver: bridge